# -*- coding: utf-8 -*-
"""Słowniki słów kluczowych – DE Ost GU: Neubau + Umbau/Modernisierung marketów (Serper, www)."""

SERPER_DISCOVERY_REGION_SUFFIX = (
    "Brandenburg Sachsen Thüringen Ostdeutschland Kleinstadt Landkreis Dorf regional "
    "Generalunternehmer Hochbau Filialneubau Filialumbau Marktmodernisierung "
    "Gewerbebau mittelständisch Referenzprojekte"
)

SERPER_DISCOVERY_TERMS = [
    "Bauunternehmen Ladenbau mittelständisch Brandenburg Aldi Referenz",
    "Generalunternehmer Filialbau Familienunternehmen Sachsen Rewe",
    "Ladenbau Meisterbetrieb Thüringen Kaufland Neubau",
    "Bauunternehmen Discounter Filialneubau regional Brandenburg Penny",
    "Generalunternehmer Einzelhandelsbau klein Leipzig Netto",
    "Ladenbau Generalunternehmer Dresden Aldi Referenzprojekte",
    "Bauunternehmen Supermarktbau inhabergeführt Chemnitz Rewe",
    "Generalunternehmer Filialbau Cottbus Kaufland",
    "Ladenbau regional Potsdam Netto Marktbau",
    "Bauunternehmen Einzelhandel Erfurt Penny Referenzen",
    "Generalunternehmer Marktbau Halle Saale Lidl",
    "Ladenbau Generalunternehmer Jena Rewe Filiale",
    "Bauunternehmen Ladenbau Landkreis Barnim Familienbetrieb Aldi",
    "Generalunternehmer Filialbau Uckermark Kleinstadt Rewe",
    "Ladenbau Meisterbetrieb Bautzen Oberlausitz Kaufland",
    "Bauunternehmen Discounter Neubau Prignitz regional Penny",
    "Generalunternehmer Einzelhandel Spree-Neiße Cottbus Umland Netto",
    "Ladenbau GU Erzgebirge Annaberg-Buchholz Aldi Referenz",
    "Bauunternehmen Filialbau Vogtland Plauen inhabergeführt",
    "Generalunternehmer Ladenbau Kyffhäuserkreis Thüringen Rewe",
    "Ladenbau regional Elbe-Elster Herzberg Kaufland",
    "Bauunternehmen mittelständisch Oberspreewald-Lausitz Senftenberg",
    "Generalunternehmer Discounter Filialneubau Saale-Orla-Kreis",
    "Ladenbau Generalunternehmer Altmark Gardelegen regional",
    "Bauunternehmen Aldi Neubau Märkisch-Oderland Bad Freienwalde",
    "Generalunternehmer Rewe Filialbau Görlitz Landkreis",
    "Ladenbau Meisterbetrieb Zwickau Erzgebirgskreis Netto",
    "Bauunternehmen Einzelhandel Weimar Umland Thüringen Penny",
    "Generalunternehmer Filialbau Nordwestuckermark Prenzlau klein",
    "Ladenbau GU Torgau-Oschatz Nordsachsen Aldi Referenz",
    "Generalunternehmer Hochbau Filialbau Aldi Brandenburg Referenz",
    "GU Hochbau Supermarkt Neubau Sachsen Rewe",
    "Bauunternehmen Hochbau Discounter Kaufland Thüringen",
    "Generalunternehmer Hoch- und Rohbau Filiale Leipzig Netto",
    "Hochbau Generalunternehmer Marktbau Dresden Penny",
    "GU Hochbau Einzelhandelsimmobilie Cottbus Lidl",
    "Generalunternehmer Gewerbebau Einzelhandel Halle Aldi",
    "Hochbau GU Filialneubau Erfurt Rewe regional",
    "Generalunternehmer Hochbau Handelsimmobilie Chemnitz Kaufland",
    "Bauunternehmen Hochbau Filialumbau Bautzen Edeka",
    "GU Hochbau Discounter Neubau Prignitz Penny",
    "Generalunternehmer Hochbau Marktbau Landkreis Barnim Netto",
    "Generalunternehmer Hochbau schlüsselfertig Filiale Aldi Brandenburg",
    "GU Hoch- und Rohbau Discounter Neubau Sachsen Rewe Referenz",
    "Komplettgeneralunternehmer Supermarktbau Kaufland Thüringen",
    "Bauunternehmen Hochbau Handelsimmobilie Leipzig Netto",
    "Generalunternehmer Gewerbebau Einzelhandel Dresden Penny",
    "Hochbau GU Filialgebäude Cottbus Lidl regional",
    "Generalunternehmer Stahlbau Markt Neubau Chemnitz Aldi",
    "Bauunternehmen Rohbau Filialneubau Erfurt Rewe",
    "GU Totalausführung Discounter Umbau Brandenburg Kaufland",
    "Hochbau Generalunternehmer Hallenbau Supermarkt Halle Edeka",
    "Generalunternehmer Filialbau aus einer Hand Jena Netto",
    "Bauunternehmen Hochbau Filialsanierung Bautzen Penny",
    "GU Komplettbau Einzelhandelsimmobilie Vogtland Plauen",
    "Generalunternehmer Hochbau Marktbau Landkreis Spree-Neiße",
    "Bauunternehmer Filialprojekt Aldi Neubau Uckermark",
    "Hochbau GU Discounter Revitalisierung Görlitz Rewe",
    "Generalunternehmer Handelsbau Familienbetrieb Prignitz Lidl",
    "Bauunternehmen Hochbau Filialstandort Erzgebirge Kaufland",
    "GU Hochbau Nahversorger Neubau Kyffhäuserkreis",
    "Generalunternehmer Einzelhandelsneubau Altmark Gardelegen Aldi",
    "Hochbau Generalunternehmer SB-Warenhaus Umbau Leipzig",
    "Bauunternehmen Hochbau Verbrauchermarkt Neubau Saalfeld",
    "GU Filialbau Rollout regional Brandenburg Edeka",
    "Generalunternehmer Hochbau Markterweiterung Dresden Netto",
    "Bauunternehmen schlüsselfertig Filialbau Senftenberg Penny",
    "Generalunternehmer Komplettbau Filialneubau Lausitz Rewe",
    "Hauptauftragnehmer Hochbau Einzelhandel Potsdam Aldi",
    "Bauunternehmen Massivbau Discounter Neubau Görlitz",
    "GU schlüsselfertige Übergabe Supermarkt Chemnitz Lidl",
    "Generalunternehmer Marktumbau Filialmodernisierung Brandenburg",
    "GU Filialumbau Supermarkt Revitalisierung Sachsen",
    "Generalunternehmer Umbau Discounter Thüringen Referenz",
    "Komplettgeneralunternehmer Marktmodernisierung Rewe regional",
    "Generalunternehmer Filialumbau Aldi Umbau Leipzig",
    "GU Lebensmittelmarkt Modernisierung Dresden",
    "Generalunternehmer Bestandsumbau Filiale Edeka Cottbus",
]

SERPER_DISCOVERY_FALLBACK_TERMS = [
    "Generalunternehmer Einzelhandelsbau Brandenburg",
    "Generalunternehmer Hochbau Filialbau Sachsen",
    "Generalunternehmer Filialbau Thüringen",
    "Generalunternehmer Aldi Neubau Ostdeutschland",
    "Generalunternehmer Kaufland Bauprojekt",
    "Generalunternehmer Rewe Filialbau",
    "Ladenbau Generalunternehmer Leipzig",
    "Generalunternehmer Discounter Dresden",
    "Generalunternehmer Einzelhandel Erfurt",
    "Generalunternehmer Supermarktbau Chemnitz",
    "Generalunternehmer Penny Filialneubau",
    "Generalunternehmer Netto Marktbau",
    "Ladenbau Generalunternehmer Kleinort Brandenburg Landkreis",
    "Bauunternehmen Filialbau Dorf Sachsen regional",
    "Generalunternehmer Ladenbau Gemeinde Thüringen",
    "Generalunternehmer Hochbau Einzelhandel Brandenburg",
    "GU Hochbau Filialbau Sachsen",
    "Hochbau Generalunternehmer Discounter Thüringen",
    "Generalunternehmer Hochbau Supermarktbau Ostdeutschland",
    "Bauunternehmen Hochbau Marktbau regional",
    "Komplettgeneralunternehmer Einzelhandel Ostdeutschland",
    "Generalunternehmer Handelsbau Referenz",
    "GU Rohbau Filialbau",
    "Generalunternehmer schlüsselfertig Discounter",
    "Hochbau Generalunternehmer Familienunternehmen",
    "Generalunternehmer Marktumbau Filialumbau",
    "GU Supermarkt Modernisierung Umbau Ostdeutschland",
    "Generalunternehmer Filialrevitalisierung Discounter",
]

GU_ROLE_KEYWORDS = (
    "generalunternehmer",
    "generalunternehmen",
    "generalunternehmerleistung",
    "komplettgeneralunternehmer",
    "komplettgeneralunternehmerleistung",
    "hauptauftragnehmer",
    "totalunternehmer",
    "bauunternehmen",
    "bauunternehmung",
    "bauausführender",
    "bauausfuehrender",
    "bauausführung",
    "bauausfuehrung",
    "generalübernehmer",
    "generaluebernehmer",
    "gu-leistung",
    "gu ",
)

# Obowiązkowe sieci w referencjach / na stronie (bez wzmianki → odrzucenie)
REQUIRED_RETAIL_CHAIN_KEYWORDS = (
    "aldi",
    "rewe",
    "edeka",
    "netto",
    "penny",
    "kaufland",
    "norma",
)

RETAIL_CHAIN_KEYWORDS = (
    "aldi",
    "aldi nord",
    "aldi süd",
    "aldi sued",
    "penny",
    "kaufland",
    "netto",
    "netto marken-discount",
    "rewe",
    "rewe group",
    "lidl",
    "edeka",
    "norma",
    "nahkauf",
    "toom",
    "tegut",
    "marktkauf",
    "hit ",
    "famila",
    "combi",
    "globus",
    "selgros",
    "metro",
    "rossmann",
    "action",
    "takko",
    "kik",
    "woolworth",
)

RETAIL_BUILD_KEYWORDS = (
    *GU_ROLE_KEYWORDS,
    "hochbau",
    "hoch- und rohbau",
    "hoch und rohbau",
    "rohbau",
    "rohbauarbeiten",
    "geschäftsbau",
    "geschaftsbau",
    "gewerbebau",
    "hallenbau",
    "industriebau",
    "stahlbau",
    "stahlbauhallen",
    "massivbau",
    "betonbau",
    "schlüsselfertigbau",
    "schluesselfertigbau",
    "schlüsselfertig",
    "schluesselfertig",
    "komplettbau",
    "komplettsanierung",
    "totalausführung",
    "totalausfuehrung",
    "totalauftrag",
    "aus einer hand",
    "alle gewerke aus einer hand",
    "schlüsselfertige übergabe",
    "schluesselfertige uebergabe",
    "rohbau bis fertigstellung",
    "komplette baumaßnahme",
    "komplette baumassnahme",
    "neubau",
    "umbau",
    "erweiterung",
    "erweiterungsbau",
    "anbau",
    "sanierung",
    "revitalisierung",
    "modernisierung",
    "generalsanierung",
    "abriss und neubau",
    "neubau filiale",
    "filialneubau",
    "filialumbau",
    "filialsanierung",
    "markterweiterung",
    "ladenerweiterung",
    "handelsbau",
    "handelsimmobilien",
    "filialgebäude",
    "filialgebaude",
    "filialstandort",
    "filialobjekt",
    "einzelhandelsimmobilie",
    "handelsimmobilie",
    "supermarkt-neubau",
    "supermarktneubau",
    "supermarktbau",
    "discounter-neubau",
    "discounterbau",
    "marktneubau",
    "ladenbau",
    "filialbau",
    "einzelhandelsbau",
    "einzelhandel",
    "einzelhandelsneubau",
    "discounter",
    "supermarkt",
    "marktbau",
    "handelsimmobil",
    "lebensmitteleinzelhandel",
    "food retail",
    "markterneuerung",
    "nahversorger",
    "verbrauchermarkt",
    "vollsortimenter",
    "sb-warenhaus",
    "handelsmarkt",
    "handelsprojekt",
    "einzelhandelsprojekt",
    "filialprojekt",
    "bauprojekt einzelhandel",
    "gewerbeimmobilie einzelhandel",
)

# Einzelhandel / Filialbau / Hochbau sklepów — bez wymogu Aldi/Rewe ani sekcji Referenzen
RETAIL_TRADE_ACTIVITY_KEYWORDS = (
    "filialbau",
    "ladenbau",
    "marktbau",
    "supermarktbau",
    "supermarkt-neubau",
    "supermarktneubau",
    "einzelhandelsbau",
    "handelsbau",
    "discounter",
    "discounterbau",
    "supermarkt",
    "einzelhandel",
    "lebensmitteleinzelhandel",
    "filialneubau",
    "filialumbau",
    "filialsanierung",
    "filialgebäude",
    "filialgebaude",
    "filialstandort",
    "einzelhandelsimmobilie",
    "handelsimmobilie",
    "handelsimmobilien",
    "handelsmarkt",
    "handelsprojekt",
    "einzelhandelsprojekt",
    "filialprojekt",
    "nahversorger",
    "verbrauchermarkt",
    "sb-warenhaus",
    "marktneubau",
    "markterweiterung",
    "ladenerweiterung",
    "filial",
)

RETAIL_HOCHBAU_CORE_KEYWORDS = (
    "hochbau",
    "hoch- und rohbau",
    "hoch und rohbau",
    "rohbau",
    "rohbauarbeiten",
    "geschäftsbau",
    "geschaftsbau",
    "gewerbebau",
    "hallenbau",
    "stahlbauhallen",
    "schlüsselfertigbau",
    "schluesselfertigbau",
    "komplettbau",
)

RETAIL_REFERENCE_KEYWORDS = (
    "referenz",
    "referenzen",
    "referenzprojekt",
    "referenzprojekte",
    "referenzliste",
    "projekte",
    "projekt",
    "projektübersicht",
    "projektuebersicht",
    "projektbeispiele",
    "bauprojekte",
    "objektübersicht",
    "objektuebersicht",
    "realisierung",
    "realisiert",
    "realisieren",
    "umgesetzt",
    "errichtet",
    "erstellt",
    "gebaut",
    "bauherr",
    "auftraggeber",
    "ausführung",
    "ausfuehrung",
    "bauleistung",
    "leistungsspektrum",
    "portfolio",
    "case study",
    "baustellen",
    "baustellenberichte",
    "unsere projekte",
)

RETAIL_URL_PRIORITY_KEYWORDS = (
    "referenz",
    "referenzen",
    "projekt",
    "projekte",
    "leistung",
    "leistungen",
    "bauleistungen",
    "ladenbau",
    "filial",
    "hochbau",
    "rohbau",
    "gewerbebau",
    "handelsbau",
    "einzelhandel",
    "discounter",
    "supermarkt",
    "marktbau",
    "markt",
    "portfolio",
    "realis",
    "bauprojekt",
    "aktuelle-projekte",
    "objekte",
    "karriere",
    "stellen",
    "jobs",
    "career",
    "auftraggeber",
)

# Typowe ścieżki Impressum (DE) — mail często tylko tam
IMPRESSUM_GUESS_PATHS = (
    "/impressum",
    "/impressum/",
    "/Impressum",
    "/de/impressum",
    "/de/impressum/",
    "/kontakt-impressum",
    "/kontakt/impressum",
    "/legal/impressum",
    "/unternehmen/impressum",
    "/site/impressum",
    "/imprint",
    "/imprint/",
)

RETAIL_CONTACT_LINK_KEYWORDS = (
    "kontakt",
    "contact",
    "impressum",
    "imprint",
    "o-nas",
    "ueber-uns",
    "über-uns",
    "referenz",
    "referenzen",
    "projekt",
    "projekte",
    "ladenbau",
    "filial",
    "hochbau",
    "rohbau",
    "gewerbebau",
    "handelsbau",
    "marktbau",
    "supermarkt",
    "anfrage",
    "leistungen",
    "bauleistungen",
    "karriere",
    "stellen",
    "stellenangebot",
    "jobs",
    "career",
)

DE_OST_REGION_KEYWORDS = (
    "neue bundesländer",
    "neue bundeslaender",
    "lausitz",
    "erzgebirge",
    "erzgebirgskreis",
    "mansfeld-südharz",
    "mansfeld-suedharz",
    "burgenlandkreis",
    "wartburgkreis",
    "unstrut-hainich",
    "ostprignitz-ruppin",
    "dahme-spreewald",
    "oder-spree",
    "havelland",
    "fläming",
    "flaeming",
    "sachsen-anhalt",
)

DE_OST_RURAL_HINTS = (
    "landkreis",
    "kreisstadt",
    "gemeinde",
    "kleinstadt",
    "ortschaft",
    " ort ",
    "dorf ",
    "dorfstraße",
    "dorfstrasse",
    "amtsbezirk",
    "verbandsgemeinde",
)

DE_OST_PLACE_MARKERS = (
    "leipzig",
    "dresden",
    "chemnitz",
    "erfurt",
    "potsdam",
    "cottbus",
    "halle",
    "jena",
    "zwickau",
    "goerlitz",
    "görlitz",
    "magdeburg",
    "ostdeutschland",
    "brandenburg",
    "sachsen",
    "thüringen",
    "thueringen",
    "wittenberge",
    "perleberg",
    "pritzwalk",
    "neuruppin",
    "rheinsberg",
    "angermünde",
    "angermuende",
    "schwedt",
    "eberswalde",
    "bernau",
    "fürstenwalde",
    "fuerstenwalde",
    "beeskow",
    "lübben",
    "luebben",
    "luckau",
    "senftenberg",
    "finsterwalde",
    "herzberg",
    "nauen",
    "rathenow",
    "luckenwalde",
    "zossen",
    "ludwigsfelde",
    "bad freienwalde",
    "seelow",
    "strausberg",
    "oranienburg",
    "falkensee",
    "werder",
    "templin",
    "prenzlau",
    "bautzen",
    "kamenz",
    "radeberg",
    "freital",
    "pirna",
    "riesa",
    "meissen",
    "meißen",
    "delitzsch",
    "torgau",
    "eilenburg",
    "borna",
    "plauen",
    "annaberg-buchholz",
    "marienberg",
    "aue",
    "schneeberg",
    "crimmitschau",
    "limbach-oberfrohna",
    "weimar",
    "apolda",
    "arnstadt",
    "ilmenau",
    "saalfeld",
    "sonneberg",
    "greiz",
    "pößneck",
    "poessneck",
    "schmalkalden",
    "meiningen",
    "suhl",
    "mühlhausen",
    "muehlhausen",
    "nordhausen",
    "eisenach",
    "gotha",
    "altenburg",
    "bad langensalza",
    "leinefelde",
    "zeulenroda",
    "saalfeld-rudolstadt",
    "gera",
    "stadtilm",
    "schleiz",
    "lobenstein",
    "gardelegen",
    "wernigerode",
    "quedlinburg",
    "halberstadt",
    "stendal",
    "salzwedel",
    "tangerhütte",
    "tangerhuette",
    "zerbst",
    "köthen",
    "koethen",
    "bitterfeld",
    "wolfen",
    "merseburg",
    "naumburg",
    "zeitz",
    "grimma",
    "döbeln",
    "doebeln",
    "wurzen",
    "oschatz",
    "finsterwalde",
    "spremberg",
    "forst",
    "guben",
    "eisenhüttenstadt",
    "eisenhuettenstadt",
    "fuerstenberg",
    "neustrelitz",
    "wolgast",
    "anklam",
    "pasewalk",
    "demmin",
    "greifswald",
    "waren",
    "neubrandenburg",
)

SERPER_POSITIVE_TERMS = (
    "kontakt",
    "impressum",
    *GU_ROLE_KEYWORDS,
    *RETAIL_BUILD_KEYWORDS,
    *RETAIL_CHAIN_KEYWORDS,
    *RETAIL_REFERENCE_KEYWORDS,
    "filiale",
    "neubau",
    "umbau",
    "sanierung",
    "revitalisierung",
    "erweiterung",
    "ostdeutschland",
    "brandenburg",
    "sachsen",
    "thüringen",
    "thueringen",
    "leipzig",
    "dresden",
    "chemnitz",
    "erfurt",
    "cottbus",
    "halle",
    "landkreis",
    "kleinstadt",
    "gemeinde",
    "regional",
    "mittelständisch",
    "mittelstaendisch",
    "familienunternehmen",
    "meisterbetrieb",
    "inhabergeführt",
    "inhabergefuehrt",
    *DE_OST_REGION_KEYWORDS,
    *DE_OST_PLACE_MARKERS[:40],
)

SERPER_NEGATIVE_TERMS = (
    "vergabemarktplatz",
    "ausschreibung",
    "stadt leipzig",
    "stadt erfurt",
    "dezernat",
    "landkreis",
    "gemeinde ",
    "ihk ",
    "handelskammer",
    "wirtschaftsförderung",
    "gründerzentrum",
    "technologiezentrum",
    "hochschule",
    "universität",
    "ministerium",
    "senatskanzlei",
    "forum",
    "blog.",
    "11880.com",
    "11880.",
    "wikipedia",
    "olx",
    "allegro",
    "amazon.",
    "ebay.",
    "praca",
    "kariera",
    "oferty pracy",
    "poradnik",
    "tutorial",
    "diy ",
    "agregat",
    "stellenangebot",
    "karriere",
    "öffnungszeiten",
    "oeffnungszeiten",
    "filialfinder",
    "wochenangebot",
    "shopfitting",
    "ladeneinrichtung",
    "ladenausstattung",
    "ladenausbau",
    "einrichtungshaus",
    "store design",
    "innenausbau",
    "innenausstatter",
    "messebau",
    "küchenbau",
    "kuechenbau",
    "möbelbau",
    "moebelbau",
    "architekturbüro",
    "architekturbuero",
    "planungsbüro",
    "planungsbuero",
    "fachplanung",
    "projektsteuerung",
    "projektentwickler",
    "facility management",
    "gebäudereinigung",
    "gebaeudereinigung",
    "immobilienmakler",
    "straßenbau",
    "strassenbau",
    "kanalbau",
    "gartenbau",
    "dachdecker",
    "malerbetrieb",
    "elektroinstallateur",
    "strabag",
    "hochtief",
    "bilfinger",
    "porr.de",
    "porr ",
    "goldbeck",
    "implenia",
    "zech group",
    "max bögl",
    "max boegl",
    "züblin",
    "zueblin",
    "leonhard weiss",
    "habau",
    "vinci",
    "bouygues",
    "konzern",
    "weltweit",
    "internationaler konzern",
)

LARGE_COMPANY_DOMAINS_EXTRA = frozenset(
    {
        "max-boegl.de",
        "ed-zueblin.de",
        "leonhard-weiss.de",
        "habau.com",
        "vinci.com",
        "porr.de",
    }
)

LARGE_COMPANY_NAME_MARKERS_EXTRA = (
    "max bögl",
    "max boegl",
    "ed. züblin",
    "züblin",
    "leonhard weiss",
    "habau",
)

SMALL_COMPANY_PAGE_MARKERS_EXTRA = (
    "ortsansässig",
    "ortsansaessig",
    "inhabergeführtes bauunternehmen",
    "inhabergefuehrtes bauunternehmen",
    "traditionsreiches bauunternehmen",
    "inhabergeführtes unternehmen",
    "inhabergefuehrtes unternehmen",
    "überregional",
    "ueberregional",
)

SMALL_COMPANY_DISCOVERY_TERMS_EXTRA = (
    "mittelständisch",
    "mittelstaendisch",
    "inhabergefuehrt",
    "familienbetrieb",
    "ortsansässig",
    "ortsansaessig",
    "traditionsreich",
    "hochbau",
    "schlüsselfertig",
    "schluesselfertig",
    "komplettbau",
    "filialneubau",
    "handelsbau",
)
